### ISSUE TITLE
FlatImages take a while to run when `/tmp/fim` hasn't been set up yet

### ISSUE THREAD

**Issue by hwittenborn** [ruanformigoni/flatimage#18]
I noticed that FlatImages take quite a while to run (~10 seconds in my testing) when the image hasn't been set in `/tmp/fim` yet. I'm really wanting to avoid this, as my use case may involve `/tmp` being empty on each application run.

I'm not sure exactly on the underlying cause, but I'm assuming this is due to extracting the image. I haven't been able to do much profiling yet, but maybe allowing a FlatImage to be ran directly from a pre-extracted directory could help out the situation?

**Comment by ruanformigoni** [comment]
Hi @hwittenborn , this is due to the application binary extraction. I can try to search `~/.cache` for the temporary binaries, which would not be erased on a system restart. Other improvements could be to integrate `fuse2fs` and `e2fsck` into the main binary, which would reduce the copy time, or try to improve the binary writing function.

**Comment by ruanformigoni** [comment]
It should now be satisfactory with v0.2.1, I'll log further improvements to startup time here as they come :grin:
